import type { NextPage } from "next";
import Head from "next/head";
import Accordion from "../components/Accordian";
import { Column, PageWrapper } from "../components/Layout";
import { Navigation } from "../components/Navigation";
import { Heading } from "../components/Typography";
import { trpc } from "../utils/trpc";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <PageWrapper>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <Column>
        <div className="relative w-full overflow-hidden rounded-xl bg-blue-500 px-8 py-10 md:px-12 md:py-20 lg:py-40 lg:px-28">
          <div className="opacity-4 60 absolute left-0 bottom-0 top-0">
            <Image
              src="/assets/bg_doce.png"
              layout="intrinsic"
              alt="bg doce"
              width={3176}
              height={1880}
            />
          </div>

          <div className="absolute top-1/4 left-[-7%] -translate-y-1/2 transform">
            <Image
              src="/assets/gradient_two.png"
              layout="intrinsic"
              width={1250}
              height={1250}
              alt="gradient"
            />
          </div>

          <Heading className="relative !text-white">
            The future of <br />
            development
          </Heading>
        </div>

        <Heading>
          Create <span className="text-purple-300">T3</span> App
        </Heading>
        <p className="text-2xl text-gray-700">This stack uses:</p>

        <Accordion />

        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </Column>
    </PageWrapper>
  );
};

export default Home;
