import Accordion from "../components/Accordian";
import { Image } from "../components/Image";
import { InnerColumn, OuterColumn, PageWrapper, Section } from "../components/Layout";
import { Navigation } from "../components/Navigation";
import { Heading } from "../components/Typography";
import type { NextPage } from "next";
import Head from "next/head";
import tw from "twin.macro";

const Home: NextPage = () => {
	return (
		<PageWrapper>
			<Head>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />

			<OuterColumn>
				<div className="relative w-full overflow-hidden rounded-xl bg-blue-500">
					<div className="opacity-4 60 absolute left-0 bottom-0 top-0">
						<Image
							src="/assets/bg_doce.png"
							layout="intrinsic"
							alt="bg doce"
							width={3176}
							priority={false}
							height={1880}
							placeholder="empty"
							wrapperClass={tw`delay-[2s] duration-1000`}
						/>
					</div>

					<div className="absolute top-1/4 left-[-7%] -translate-y-1/2 transform">
						<Image
							src="/assets/gradient_two.png"
							layout="intrinsic"
							width={1250}
							height={1250}
							alt="gradient"
							placeholder="empty"
							wrapperClass={tw`delay-300 duration-1000`}
						/>
					</div>

					<InnerColumn className="py-10 md:py-20 lg:py-40">
						<Heading className="relative !text-white">
							The future of <br />
							development
						</Heading>
					</InnerColumn>
				</div>

				<Section>
					<InnerColumn halfWidth>
						<Accordion />
					</InnerColumn>
				</Section>
			</OuterColumn>
		</PageWrapper>
	);
};

export default Home;
