import type { NextPage } from "next";
import Head from "next/head";
import Accordion from "../components/Accordian";
import { Column, PageWrapper } from "../components/Layout";
import { Navigation } from "../components/Navigation";
import { Heading } from "../components/Typography";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <Navigation />

        <Column>
          <div className="h-96 w-full overflow-hidden rounded-xl bg-blue-500">
            <Heading className="!text-white">Create Cool App</Heading>
          </div>

          <Accordion />
        </Column>
      </PageWrapper>
    </>
  );
};

export default Home;
